fastboot flash system 01system.img
fastboot flash vendor 02vendor.img
fastboot flash boot 03boot.img
fastboot flash cmnlib64 04cmnlib64.mbn
fastboot flash vbmeta 05vbmeta.img
fastboot flash splash 06splash.img
fastboot flash cmnlib 07cmnlib.mbn
fastboot flash hyp 08hyp.mbn
fastboot flash tz 09tz.mbn
fastboot flash aop 10aop.mbn
fastboot flash xbl_config 11xbl_config.elf
fastboot flash keymaster 12keymaster64.mbn
fastboot flash qupfw 13qupv3fw.elf
fastboot flash abl 14abl.elf
fastboot flash dtbo 15dtbo.img
fastboot flash devcfg 16devcfg.mbn
fastboot flash storsec 17storsec.mbn
fastboot flash xbl 18xbl.elf
fastboot flash dsp 19dspso.bin
fastboot flash modem 20NON-HLOS.bin
fastboot flash bluetooth 21BTFM.bin
fastboot reboot